---

- name: add static entries to /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for item in service_dnsmasq_static_host_entries -%}
      {{ item.ip }} {{ item.name }}
      {% endfor %}
    marker: "# {mark} ansible section - static entries also used by dnsmasq"
  when: ((service_dnsmasq_service_dnsmasq_static_host_entriesc_names | default([])) or []) | length > 0
